# Generated by Django 3.2.25 on 2024-03-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Std',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accepted'), ('reject', 'Rejected')], default='pending', max_length=10)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_number', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
