# Generated by Django 5.0.3 on 2024-03-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0002_std_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
