# Generated by Django 5.0.3 on 2024-03-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0003_alter_std_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='std',
            name='photo',
        ),
        migrations.AddField(
            model_name='std',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='std',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
