# Generated by Django 5.0.3 on 2024-03-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0004_remove_std_photo_std_in_time_std_out_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='std',
            name='in_time',
        ),
        migrations.RemoveField(
            model_name='std',
            name='out_time',
        ),
    ]
