# Generated by Django 5.0.1 on 2024-05-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pass", "0005_remove_std_in_time_remove_std_out_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="std",
            name="hod_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accept", "Accepted"),
                    ("reject", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="std",
            name="incharge_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accept", "Accepted"),
                    ("reject", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
