# Generated by Django 5.0.1 on 2024-05-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pass", "0007_alter_std_hod_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="std",
            name="hod_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accept", "Accepted"),
                    ("reject", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
