# Generated by Django 5.0.1 on 2024-05-04 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pass", "0008_alter_std_hod_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="std",
            name="status",
        ),
    ]
