# Generated by Django 5.0.1 on 2024-05-05 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pass", "0010_alter_std_hod_status_alter_std_incharge_status_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
