# Generated by Django 5.0.1 on 2024-05-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pass", "0013_remove_profile_user_userprofile_delete_customuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="std",
            name="hod_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("ACCEPTED", "ACCEPTED"),
                    ("REJECTED", "REJECTED"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="std",
            name="incharge_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("ACCEPTED", "ACCEPTED"),
                    ("REJECTED", "REJECTED"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "student"),
                    ("incharge", "incharge"),
                    ("hod", "hod"),
                    ("warden", "warden"),
                    ("security", "security"),
                ],
                max_length=20,
            ),
        ),
    ]
